### ISSUE TITLE
TypeScript speed does not "continue to be fast regardless of the size of the project"

### ISSUE THREAD

**Issue by bcherny** [niieani/typescript-vs-flowtype#16]
See https://github.com/Microsoft/TypeScript/issues/13538

**Comment by niieani** [comment]
The note regards only type-checking time, not transpilation time (since Flow is not a transpiler). It's a valid point though, we should clear it up.

Naturally, the total speed is going to go down with the size of the project, though the relation is more like `O(n)` in the case of TypeScript, and `O(n^2)` in the case of Flow. These are purely observational, and we need solid benchmarks to prove or disprove my claims.
